# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Java CI

on:
  push:
    tags: ['*.*.*']

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: write
      discussions: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      # TODO (mod-squad): Add S3 fetching routine to pull in WSE dependencies.
      - name: Configure AWS credentials for hub account
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.HUB_ACCOUNT_ROLE_ARN }}
          role-session-name: ${{ secrets.HUB_ACCOUNT_ROLE_SESSION_NAME }}
      - name: Configure AWS Credentials for spoke account
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.SPOKE_ACCOUNT_ROLE_ARN }}
          role-session-name: ${{ secrets.SPOKE_ACCOUNT_ROLE_SESSION_NAME }}
          role-chaining: true
          role-skip-session-tagging: true
      - name: Copy WSE distribution from S3
        run: |
          aws s3 cp s3://${{ secrets.WOWZA_DISTRIBUTION_BUCKET }}/${{ vars.WOWZA_RELEASE_CHANNEL }}/${{ vars.WOWZA_VERSION }}/WowzaStreamingEngine-Update-${{ vars.WOWZA_VERSION }}.zip .
      - name: Unzip WSE distribution
        run: |
          unzip WowzaStreamingEngine-Update-${{ vars.WOWZA_VERSION }}.zip -d ${{ vars.WSE_HOME }}
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build Gradle
        run: gradle build -Pversion=${{ github.ref_name }} -PwseLibDir=${{ vars.WSE_HOME }}/files/lib
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          discussion_category_name: announcements
          generate_release_notes: true
          files: |
            build/libs/*
